spring.application.name=Vehicle-Insurance-Compliance-Tracker



spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_tracking_system_db
spring.datasource.username=postgres
spring.datasource.password=Mastek12
spring.jpa.hibernate.ddl-auto=update
