spring.application.name=Vehicle-Insurance-Compliance-Tracker



server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_tracking_system_db
spring.datasource.username=postgres
spring.datasource.password=Mastek12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



aws.region=eu-west-1
aws.s3.bucket-name=twoja-nazwa-bucketa
aws.accessKeyId=TWOJ_ACCESS_KEY
aws.secretKey=TWOJ_SECRET_KEY


#spring.datasource.url=jdbc:postgresql://db:5432/compliance_db
#spring.datasource.username=postgres
#spring.datasource.password=Mastek12
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#server.port=8080