#spring.datasource.url=jdbc:postgresql://db:5432/compliance_db
#spring.datasource.username=postgres
#spring.datasource.password=Mastek12
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#server.port=8080