apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: vehicle-compliance
type: Opaque
stringData:
  AWS_REGION: eu-west-1
  AWS_ACCESSKEYID: replace-me
  AWS_SECRETKEY: replace-me
  SPRING_CLOUD_AWS_REGION_STATIC: eu-west-1
  SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY: replace-me
  SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY: replace-me
  AWS_S3_BUCKET_NAME: replace-me
