apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: vehicle-compliance
type: Opaque
stringData:
  AWS_REGION: eu-west-1
  AWS_ACCESSKEYID: replace-me
  AWS_SECRETKEY: replace-me
  AWS_S3_BUCKET_NAME: replace-me
