apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: vehicle-compliance
type: Opaque
stringData:
  POSTGRES_DB: vehicle_tracking_system_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Mastek12
